/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrderOrderIdIndexRouteImport } from './routes/order/$orderId/index'
import { Route as AdminSignupIndexRouteImport } from './routes/admin/signup/index'
import { Route as AdminQueueIndexRouteImport } from './routes/admin/queue/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminMenuIndexRouteImport } from './routes/admin/menu/index'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminInvitesIndexRouteImport } from './routes/admin/invites/index'
import { Route as AdminSignupInviteCodeIndexRouteImport } from './routes/admin/signup/$inviteCode/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdIndexRoute = OrderOrderIdIndexRouteImport.update({
  id: '/order/$orderId/',
  path: '/order/$orderId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupIndexRoute = AdminSignupIndexRouteImport.update({
  id: '/admin/signup/',
  path: '/admin/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueIndexRoute = AdminQueueIndexRouteImport.update({
  id: '/admin/queue/',
  path: '/admin/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/admin/profile/',
  path: '/admin/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuIndexRoute = AdminMenuIndexRouteImport.update({
  id: '/admin/menu/',
  path: '/admin/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/admin/login/',
  path: '/admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesIndexRoute = AdminInvitesIndexRouteImport.update({
  id: '/admin/invites/',
  path: '/admin/invites/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupInviteCodeIndexRoute =
  AdminSignupInviteCodeIndexRouteImport.update({
    id: '/admin/signup/$inviteCode/',
    path: '/admin/signup/$inviteCode/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/menu': typeof MenuIndexRoute
  '/admin/invites': typeof AdminInvitesIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/queue': typeof AdminQueueIndexRoute
  '/admin/signup': typeof AdminSignupIndexRoute
  '/order/$orderId': typeof OrderOrderIdIndexRoute
  '/admin/signup/$inviteCode': typeof AdminSignupInviteCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/menu': typeof MenuIndexRoute
  '/admin/invites': typeof AdminInvitesIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/menu': typeof AdminMenuIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/queue': typeof AdminQueueIndexRoute
  '/admin/signup': typeof AdminSignupIndexRoute
  '/order/$orderId': typeof OrderOrderIdIndexRoute
  '/admin/signup/$inviteCode': typeof AdminSignupInviteCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/admin/invites/': typeof AdminInvitesIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/menu/': typeof AdminMenuIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/queue/': typeof AdminQueueIndexRoute
  '/admin/signup/': typeof AdminSignupIndexRoute
  '/order/$orderId/': typeof OrderOrderIdIndexRoute
  '/admin/signup/$inviteCode/': typeof AdminSignupInviteCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/menu'
    | '/admin/invites'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/profile'
    | '/admin/queue'
    | '/admin/signup'
    | '/order/$orderId'
    | '/admin/signup/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/menu'
    | '/admin/invites'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/profile'
    | '/admin/queue'
    | '/admin/signup'
    | '/order/$orderId'
    | '/admin/signup/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/checkout/'
    | '/menu/'
    | '/admin/invites/'
    | '/admin/login/'
    | '/admin/menu/'
    | '/admin/profile/'
    | '/admin/queue/'
    | '/admin/signup/'
    | '/order/$orderId/'
    | '/admin/signup/$inviteCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  MenuIndexRoute: typeof MenuIndexRoute
  AdminInvitesIndexRoute: typeof AdminInvitesIndexRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
  AdminMenuIndexRoute: typeof AdminMenuIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminQueueIndexRoute: typeof AdminQueueIndexRoute
  AdminSignupIndexRoute: typeof AdminSignupIndexRoute
  OrderOrderIdIndexRoute: typeof OrderOrderIdIndexRoute
  AdminSignupInviteCodeIndexRoute: typeof AdminSignupInviteCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId/': {
      id: '/order/$orderId/'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup/': {
      id: '/admin/signup/'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue/': {
      id: '/admin/queue/'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu/': {
      id: '/admin/menu/'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites/': {
      id: '/admin/invites/'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup/$inviteCode/': {
      id: '/admin/signup/$inviteCode/'
      path: '/admin/signup/$inviteCode'
      fullPath: '/admin/signup/$inviteCode'
      preLoaderRoute: typeof AdminSignupInviteCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  MenuIndexRoute: MenuIndexRoute,
  AdminInvitesIndexRoute: AdminInvitesIndexRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
  AdminMenuIndexRoute: AdminMenuIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminQueueIndexRoute: AdminQueueIndexRoute,
  AdminSignupIndexRoute: AdminSignupIndexRoute,
  OrderOrderIdIndexRoute: OrderOrderIdIndexRoute,
  AdminSignupInviteCodeIndexRoute: AdminSignupInviteCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
